export const ADD_ARTICLE = "ADD_ARTICLE";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_LOGGED = "FETCH_USER_LOGGED";
