export const ADD_ARTICLE = "ADD_ARTICLE";
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
export const FETCH_USER_LOGGED = "FETCH_USER_LOGGED";
export const FETCH_CURRENT_DAY = "FETCH_CURRENT_DAY";
export const FETCH_CURRENT_FULFILLED = "FETCH_CURRENT_FULFILLED";
export const FETCH_LOGIN_IN_FULFILLED = "FETCH_LOGIN_IN_FULFILLED";
export const FETCH_LOGIN_OUT_FULFILLED = "FETCH_LOGIN_OUT_FULFILLED";
export const FETCH_WEEKS_FULFILLED = "FETCH_WEEKS_FULFILLED";
export const FETCH_WEEK_HOURS_FULFILLED = "FETCH_WEEK_HOURS_FULFILLED";
export const FETCH_DAY_HORS_FULFILLED  = "FETCH_DAY_HORS_FULFILLED ";
export const ADD_HOUR = "ADD_HOUR";
export const UPDATED_HOUR = "UPDATED_HOUR";

